#!/usr/bin/env python3
"""
Converted from ruby: test_ruby.rb
Generated by MCP Multi-Language to Python Converter
"""

import os
import sys
import subprocess
import logging
from pathlib import Path
from typing import Optional, List, Dict, Any

# Setup logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

#!/usr/bin/env python3

import sys
import logging
import boto3
from botocore.exceptions import BotoCoreError, ClientError

# Set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def create_s3_bucket(bucket_name: str, region: str = "us-east-1") -> None:
    """
    Create an S3 bucket in a specified region.

    :param bucket_name: Name of the bucket to create.
    :param region: Region to create the bucket in. Default is 'us-east-1'.
    :return: None
    """
    try:
        s3_client = boto3.client('s3', region_name=region)
        location = {'LocationConstraint': region}
        s3_client.create_bucket(Bucket=bucket_name, CreateBucketConfiguration=location)
    except (BotoCoreError, ClientError) as error:
        logger.error(f"Failed to create bucket. Error: {error}")
        sys.exit(1)
    else:
        logger.info(f"Bucket '{bucket_name}' created successfully in region '{region}'.")

def main():
    # Get the bucket name from command line
    bucket_name = sys.argv[1] if len(sys.argv) > 1 else None

    # Validate input
    if not bucket_name:
        logger.error("Usage: python create_s3_bucket.py <bucket-name>")
        sys.exit(1)

    # Create the S3 bucket
    create_s3_bucket(bucket_name)

if __name__ == "__main__":
    main()